title: Sir
author: Quy Le
email: lengocquytp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Computer Engineering student at UT Dallas. Hifi lover, PC enthusiast,
  Video Game expert, Art admirer.

# social links
twitter_username: VincentQuy # DO NOT include the @ character, or else the build will fail!
github_username:  vincentquy # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
